const CardData = [
    {
        key : 1,
        firstName : "Weather App",
        pera : "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam, praesentium.",
        li1 : "React JS",
        li2 : "React Hooks",
        li3 : "Material UI",
        li4 : "API",
        atribute : "Weather App",
        link : "https://thefurqanrahim.github.io/Weather/",
    },
    {
        key : 2,
        firstName : "Islamic Date",
        pera : "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam, praesentium.",
        li1 : "React JS",
        li2 : "React Hooks",
        li3 : "Material UI",
        li4 : "API",
        atribute : "Islamic Date",
        link : "https://thefurqanrahim.github.io/IslamicDates/",
    },
    {
        key : 3,
        firstName : "Todo App",
        pera : "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam, praesentium.",
        li1 : "React JS",
        li2 : "React Hooks",
        // li3 : "Three",
        // li4 : "Four",
        atribute: "Todo App",
        link : "http://thefurqanrahim.github.io/TodoApp",
    },
    {
        key : 4,
        firstName : "Bizz Communication",
        pera : "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam, praesentium.",
        li1 : "React JS (Website)",
        li2 : "React Hooks",
        li3 : "Bootstrap",
        li4 : "Props",
        atribute : "Bizz Communication",
        link : " https://thefurqanrahim.github.io/BizzCommunication/",
    },
    {
        key : 5,
        firstName : "Quiz App",
        pera : "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam, praesentium.",
        li1 : "React JS",
        li2 : "React Hooks",
        li3 : "Props",
        // li4 : "Four",
        atribute: "Quiz App",
        link : "https://project-cf43f.web.app/",
    },
    {
        key : 6,
        firstName : "Resume (CV)",
        pera : "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam, praesentium.",
        li1 : "HTML",
        li2 : "CSS",
        // li3 : "Three",
        // li4 : "Four",
        atribute : "Resume",
        link : "https://thefurqanrahim.github.io/cv.github.io/",
    },
    {
        key : 7,
        firstName : "Github",
        pera : "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam, praesentium.",
        li1 : "Github Profile",
        // li2 : "Two",
        // li3 : "Three",
        // li4 : "Four",
        atribute : "Github",
        link : "https://github.com/thefurqanrahim?tab=repositories",
    },
    {
        key : 8,
        firstName : "Graphic Designing/ Video Animation",
        // pera : "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam, praesentium.",
        li1 : "Illustrator",
        li2 : "Photoshop",
        li3 : "Premiere",
        li4 : "After Effects",
        atribute : "Graphic Designing/ Video Animation",
        link : "https://www.behance.net/thefurquanrahim",
    }
]

export default CardData;